import type { Cuisine } from '../cuisineClassifier.js';

export const CUISINE_KEYWORDS: Record<Cuisine, string[]> = {
  indian: ['thali', 'dosa', 'naan', 'roti', 'chapati', 'dal', 'curry', 'tikka', 'masala', 'biryani', 'chutney', 'paneer', 'lassi', 'samosa', 'idli', 'sambar', 'raita', 'paratha', 'kheer', 'gulab jamun', 'gajar halwa', 'halwa', 'chai', 'pakora', 'chaat', 'pulao', 'korma', 'vindaloo', 'tandoori', 'kulfi', 'papad', 'achaar', 'rasam', 'uttapam', 'kachori', 'jalebi', 'rajma', 'chana', 'pav bhaji', 'vada pav', 'ladoo', 'laddu', 'dhokla'],
  us: ['burger', 'cheeseburger', 'hamburger', 'fries', 'sandwich', 'sub', 'hot dog', 'bbq', 'brunch', 'breakfast', 'bacon', 'pancake', 'waffle', 'omelette', 'bagel', 'cereal', 'milkshake', 'mac and cheese', 'fried chicken', 'wings', 'ribs', 'ranch', 'club sandwich', 'blt', 'caesar salad', 'cobb salad', 'pulled pork', 'brisket', 'meatloaf', 'cheesesteak'],
  western: ['schnitzel', 'sauerkraut', 'bratwurst', 'croissant', 'baguette', 'brioche', 'quiche', 'crepe', 'ratatouille', 'coq au vin', 'beef bourguignon', 'fish and chips', 'shepherd', 'bangers', 'sunday roast', 'yorkshire pudding', 'fondue', 'raclette', 'goulash', 'pierogi', 'borscht', 'strudel', 'sachertorte', 'eclair'],
  eastAsian: ['ramen', 'sushi', 'sashimi', 'tempura', 'teriyaki', 'miso', 'edamame', 'gyoza', 'dim sum', 'dumpling', 'fried rice', 'chow mein', 'lo mein', 'kung pao', 'general tso', 'orange chicken', 'wonton', 'bao', 'pho', 'banh mi', 'spring roll', 'pad thai', 'pad see ew', 'tom yum', 'green curry', 'red curry', 'panang', 'satay', 'bibimbap', 'bulgogi', 'kimchi', 'hot pot', 'mapo tofu', 'udon', 'soba'],
  mediterranean: ['pizza', 'pasta', 'lasagna', 'risotto', 'gnocchi', 'ravioli', 'spaghetti', 'carbonara', 'bolognese', 'pesto', 'alfredo', 'hummus', 'falafel', 'tabbouleh', 'gyro', 'kebab', 'shawarma', 'tzatziki', 'baklava', 'dolma', 'moussaka', 'paella', 'tapas', 'gazpacho', 'feta', 'bruschetta', 'focaccia', 'caprese', 'tagine', 'couscous'],
  latin: ['taco', 'burrito', 'quesadilla', 'enchilada', 'fajita', 'tamale', 'nachos', 'salsa', 'guacamole', 'refried beans', 'mole', 'chimichanga', 'tostada', 'taquito', 'gordita', 'churro', 'flan', 'tres leches', 'arepa', 'empanada', 'pupusa', 'ceviche', 'plantain', 'tostones', 'ropa vieja', 'picadillo', 'jerk chicken', 'pernil', 'sofrito', 'chimichurri', 'feijoada', 'churrasco'],
  generic: []
};
